### ISSUE TITLE
解决 炸金花第一屏 180度旋转的问题

### ISSUE THREAD

**Issue by tokinonagare** [kevinanew/app_deploy_qipai#10]
https://github.com/kevinanew/qipai/issues/805

**Comment by tokinonagare** [comment]
更改 Infoplist 中 横屏的顺序即可;
准备先完成 #11 后, 通过 python 来更方便的更改

**Comment by kevinanew** [comment]
这个应该让具体的开发人员来做，不应该在打包的时候改

**Comment by tokinonagare** [comment]
> 这个应该让具体的开发人员来做，不应该在打包的时候改

这个是在 xcode 的 info.plist 里面修改的, 看起来他们是改不了这个地方(xcode 的相关文件是在打包的时候才生成的)

**Comment by kevinanew** [comment]
哦哦哦，了解了，那就打包的时候做吧

**Comment by tokinonagare** [comment]
完成该 issue
